[package]
name = "eldon/basicstate"
description = "BasicState without DevDeps to--hopefully--allow installation."
version = "0.2.3"
license = "MIT"
authors = ["csqrl (https://csqrl.dev)"]
contributors = ["boatbomber", "rimuy", "gaffal"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"